# Generated by Django 4.1.1 on 2022-11-12 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('nationality', models.CharField(max_length=255)),
                ('website', models.CharField(max_length=255)),
                ('height', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('genre', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('artist_id', models.IntegerField()),
            ],
        ),
    ]
